using System.Text;
using Microsoft.Extensions.Logging;

namespace CLI.Generators;

/// <summary>
/// Generates type-safe C# code for RBAC permissions from Casbin policy CSV
/// </summary>
public class PermissionGenerator(ILogger logger)
{
    private const string CsvFilePath = "Adapters/Permissions/casbin_policy.csv";
    private const string RolesOutputPath = "Shared/Permissions/Roles.cs";
    private const string ActionsOutputPath = "Shared/Permissions/Actions.cs";
    private const string ResourcesOutputPath = "Shared/Permissions/Resources.cs";

    private readonly Dictionary<string, HashSet<string>> _resourceActions = new();
    private readonly HashSet<string> _roles = new();
    private readonly HashSet<string> _allActions = new();

    /// <summary>
    /// Main generation method
    /// </summary>
    public async Task GenerateAsync()
    {
        logger.LogInformation("Reading policy CSV from {Path}", CsvFilePath);
        await ParseCsvAsync();

        logger.LogInformation("Found {RoleCount} roles, {ResourceCount} resources, {ActionCount} unique actions",
            _roles.Count, _resourceActions.Count, _allActions.Count);

        logger.LogInformation("Generating Roles.cs");
        await GenerateRolesFileAsync();

        logger.LogInformation("Generating Actions.cs");
        await GenerateActionsFileAsync();

        logger.LogInformation("Generating Resources.cs");
        await GenerateResourcesFileAsync();

        logger.LogInformation("Code generation complete");
    }

    /// <summary>
    /// Parses the Casbin policy CSV file
    /// </summary>
    private async Task ParseCsvAsync()
    {
        if (!File.Exists(CsvFilePath))
            throw new FileNotFoundException($"Policy CSV file not found: {CsvFilePath}");

        var lines = await File.ReadAllLinesAsync(CsvFilePath);
        var lineNumber = 0;

        foreach (var line in lines)
        {
            lineNumber++;
            var trimmed = line.Trim();

            // Skip empty lines and comments
            if (string.IsNullOrWhiteSpace(trimmed) || trimmed.StartsWith("#"))
                continue;

            // Parse CSV: p, role, resource, action
            var parts = trimmed.Split(',');
            if (parts.Length < 4)
            {
                logger.LogWarning("Invalid policy format at line {LineNumber}: {Line}", lineNumber, line);
                continue;
            }

            var policyType = parts[0].Trim();
            var role = parts[1].Trim();
            var resource = parts[2].Trim();
            var action = parts[3].Trim();

            // Only process policy rules (p)
            if (policyType != "p")
                continue;

            // Collect data
            _roles.Add(role);
            _allActions.Add(action);

            if (!_resourceActions.ContainsKey(resource))
                _resourceActions[resource] = new HashSet<string>();

            _resourceActions[resource].Add(action);
        }
    }

    /// <summary>
    /// Generates the Roles.cs file
    /// </summary>
    private async Task GenerateRolesFileAsync()
    {
        var sb = new StringBuilder();
        sb.AppendLine("// Code generated by CLI permission:generate; DO NOT EDIT manually.");
        sb.AppendLine($"// This file was generated at {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC");
        sb.AppendLine();
        sb.AppendLine("namespace Shared.Permissions;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Contains all role constants used in the RBAC system.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class Roles");
        sb.AppendLine("{");

        var sortedRoles = _roles.OrderBy(r => r).ToList();
        foreach (var role in sortedRoles)
        {
            var constName = ToPascalCase(role);
            sb.AppendLine($"    /// <summary>Role: {role}</summary>");
            sb.AppendLine($"    public const string {constName} = \"{role}\";");
            sb.AppendLine();
        }

        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Gets all available roles");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static IReadOnlyList<string> All { get; } = new[]");
        sb.AppendLine("    {");
        foreach (var role in sortedRoles)
        {
            var constName = ToPascalCase(role);
            sb.AppendLine($"        {constName},");
        }
        sb.AppendLine("    };");
        sb.AppendLine("}");

        await File.WriteAllTextAsync(RolesOutputPath, sb.ToString());
        logger.LogInformation("Generated {Path} with {Count} roles", RolesOutputPath, sortedRoles.Count);
    }

    /// <summary>
    /// Generates the Actions.cs file
    /// </summary>
    private async Task GenerateActionsFileAsync()
    {
        var sb = new StringBuilder();
        sb.AppendLine("// Code generated by CLI permission:generate; DO NOT EDIT manually.");
        sb.AppendLine($"// This file was generated at {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC");
        sb.AppendLine();
        sb.AppendLine("namespace Shared.Permissions;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Contains all action constants used in the RBAC system.");
        sb.AppendLine("/// Actions are accessed through their parent Resource.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class Actions");
        sb.AppendLine("{");

        var sortedActions = _allActions.OrderBy(a => a).ToList();
        foreach (var action in sortedActions)
        {
            var constName = ToPascalCase(action);
            sb.AppendLine($"    /// <summary>Action: {action}</summary>");
            sb.AppendLine($"    internal static readonly Action {constName} = new(\"{action}\");");
            sb.AppendLine();
        }

        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Gets all available actions");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static IReadOnlyList<Action> All { get; } = new Action[]");
        sb.AppendLine("    {");
        foreach (var action in sortedActions)
        {
            var constName = ToPascalCase(action);
            sb.AppendLine($"        {constName},");
        }
        sb.AppendLine("    };");
        sb.AppendLine("}");

        await File.WriteAllTextAsync(ActionsOutputPath, sb.ToString());
        logger.LogInformation("Generated {Path} with {Count} actions", ActionsOutputPath, sortedActions.Count);
    }

    /// <summary>
    /// Generates the Resources.cs file with type-safe resource classes
    /// </summary>
    private async Task GenerateResourcesFileAsync()
    {
        var sb = new StringBuilder();
        sb.AppendLine("// Code generated by CLI permission:generate; DO NOT EDIT manually.");
        sb.AppendLine($"// This file was generated at {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC");
        sb.AppendLine();
        sb.AppendLine("namespace Shared.Permissions;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Contains all resource instances used in the RBAC system.");
        sb.AppendLine("/// Use these to check permissions: await _casbin.CheckPermissionAsync(user, Resources.Equipment.Name, Resources.Equipment.Write)");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class Resources");
        sb.AppendLine("{");

        var sortedResources = _resourceActions.OrderBy(kvp => kvp.Key).ToList();

        // Generate resource classes
        foreach (var (resource, actions) in sortedResources)
        {
            var className = ToPascalCase(resource) + "Resource";
            var sortedActions = actions.OrderBy(a => a).ToList();

            sb.AppendLine($"    /// <summary>");
            sb.AppendLine($"    /// Resource: {resource}");
            sb.AppendLine($"    /// </summary>");
            sb.AppendLine($"    public sealed class {className} : ResourceBase");
            sb.AppendLine($"    {{");
            sb.AppendLine($"        internal {className}() : base(\"{resource}\") {{ }}");
            sb.AppendLine();

            // Generate action properties
            foreach (var action in sortedActions)
            {
                var propName = ToPascalCase(action);
                sb.AppendLine($"        /// <summary>Action: {action}</summary>");
                sb.AppendLine($"        public Action {propName} => Actions.{propName};");
            }

            sb.AppendLine($"    }}");
            sb.AppendLine();
        }

        // Generate resource instances
        sb.AppendLine("    // Resource instances");
        foreach (var (resource, _) in sortedResources)
        {
            var propName = ToPascalCase(resource);
            var className = propName + "Resource";
            sb.AppendLine($"    /// <summary>Resource instance for {resource}</summary>");
            sb.AppendLine($"    public static {className} {propName} {{ get; }} = new();");
            sb.AppendLine();
        }

        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Gets all available resources");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static IReadOnlyList<IResource> All { get; } = new IResource[]");
        sb.AppendLine("    {");
        foreach (var (resource, _) in sortedResources)
        {
            var propName = ToPascalCase(resource);
            sb.AppendLine($"        {propName},");
        }
        sb.AppendLine("    };");
        sb.AppendLine("}");

        await File.WriteAllTextAsync(ResourcesOutputPath, sb.ToString());
        logger.LogInformation("Generated {Path} with {Count} resources", ResourcesOutputPath, sortedResources.Count);
    }

    /// <summary>
    /// Converts a string to PascalCase
    /// </summary>
    private static string ToPascalCase(string input)
    {
        if (string.IsNullOrWhiteSpace(input))
            return input;

        // Replace separators with spaces
        var normalized = input
            .Replace("-", " ")
            .Replace("_", " ")
            .Replace(":", " ");

        // Split into words and capitalize each
        var words = normalized.Split(' ', StringSplitOptions.RemoveEmptyEntries);
        var result = new StringBuilder();

        foreach (var word in words)
        {
            if (word.Length > 0)
            {
                result.Append(char.ToUpper(word[0]));
                if (word.Length > 1)
                    result.Append(word.Substring(1).ToLower());
            }
        }

        return result.ToString();
    }
}

