// Code generated by CLI permission:generate; DO NOT EDIT manually.
// This file was generated at 2026-02-05 05:43:33 UTC

namespace Shared.Permissions;

/// <summary>
/// Contains all action constants used in the RBAC system.
/// Actions are accessed through their parent Resource.
/// </summary>
public static class Actions
{
    /// <summary>Action: acknowledge</summary>
    internal static readonly Action Acknowledge = new("acknowledge");

    /// <summary>Action: configure</summary>
    internal static readonly Action Configure = new("configure");

    /// <summary>Action: execute</summary>
    internal static readonly Action Execute = new("execute");

    /// <summary>Action: export</summary>
    internal static readonly Action Export = new("export");

    /// <summary>Action: read</summary>
    internal static readonly Action Read = new("read");

    /// <summary>Action: write</summary>
    internal static readonly Action Write = new("write");

    /// <summary>
    /// Gets all available actions
    /// </summary>
    public static IReadOnlyList<Action> All { get; } =
    [
        Acknowledge,
        Configure,
        Execute,
        Export,
        Read,
        Write
    ];
}
