// Code generated by CLI permission:generate; DO NOT EDIT manually.
// This file was generated at 2026-02-05 05:43:33 UTC

namespace Shared.Permissions;

/// <summary>
/// Contains all resource instances used in the RBAC system.
/// Use these to check permissions: await _casbin.CheckPermissionAsync(user, Resources.Equipment.Name, Resources.Equipment.Write)
/// </summary>
public static class Resources
{
    /// <summary>
    /// Resource: alert-rules
    /// </summary>
    public sealed class AlertRulesResource : ResourceBase
    {
        internal AlertRulesResource() : base("alert-rules") { }

        /// <summary>Action: read</summary>
        public Action Read => Actions.Read;
        /// <summary>Action: write</summary>
        public Action Write => Actions.Write;
    }

    /// <summary>
    /// Resource: alerts
    /// </summary>
    public sealed class AlertsResource : ResourceBase
    {
        internal AlertsResource() : base("alerts") { }

        /// <summary>Action: acknowledge</summary>
        public Action Acknowledge => Actions.Acknowledge;
        /// <summary>Action: read</summary>
        public Action Read => Actions.Read;
        /// <summary>Action: write</summary>
        public Action Write => Actions.Write;
    }

    /// <summary>
    /// Resource: alerts-config
    /// </summary>
    public sealed class AlertsConfigResource : ResourceBase
    {
        internal AlertsConfigResource() : base("alerts-config") { }

        /// <summary>Action: configure</summary>
        public Action Configure => Actions.Configure;
        /// <summary>Action: read</summary>
        public Action Read => Actions.Read;
        /// <summary>Action: write</summary>
        public Action Write => Actions.Write;
    }

    /// <summary>
    /// Resource: equipment
    /// </summary>
    public sealed class EquipmentResource : ResourceBase
    {
        internal EquipmentResource() : base("equipment") { }

        /// <summary>Action: read</summary>
        public Action Read => Actions.Read;
        /// <summary>Action: write</summary>
        public Action Write => Actions.Write;
    }

    /// <summary>
    /// Resource: equipment-config
    /// </summary>
    public sealed class EquipmentConfigResource : ResourceBase
    {
        internal EquipmentConfigResource() : base("equipment-config") { }

        /// <summary>Action: configure</summary>
        public Action Configure => Actions.Configure;
        /// <summary>Action: read</summary>
        public Action Read => Actions.Read;
        /// <summary>Action: write</summary>
        public Action Write => Actions.Write;
    }

    /// <summary>
    /// Resource: equipment-status
    /// </summary>
    public sealed class EquipmentStatusResource : ResourceBase
    {
        internal EquipmentStatusResource() : base("equipment-status") { }

        /// <summary>Action: read</summary>
        public Action Read => Actions.Read;
        /// <summary>Action: write</summary>
        public Action Write => Actions.Write;
    }

    /// <summary>
    /// Resource: ingestion
    /// </summary>
    public sealed class IngestionResource : ResourceBase
    {
        internal IngestionResource() : base("ingestion") { }

        /// <summary>Action: execute</summary>
        public Action Execute => Actions.Execute;
        /// <summary>Action: read</summary>
        public Action Read => Actions.Read;
        /// <summary>Action: write</summary>
        public Action Write => Actions.Write;
    }

    /// <summary>
    /// Resource: ingestion-config
    /// </summary>
    public sealed class IngestionConfigResource : ResourceBase
    {
        internal IngestionConfigResource() : base("ingestion-config") { }

        /// <summary>Action: configure</summary>
        public Action Configure => Actions.Configure;
        /// <summary>Action: read</summary>
        public Action Read => Actions.Read;
        /// <summary>Action: write</summary>
        public Action Write => Actions.Write;
    }

    /// <summary>
    /// Resource: ingestion-runs
    /// </summary>
    public sealed class IngestionRunsResource : ResourceBase
    {
        internal IngestionRunsResource() : base("ingestion-runs") { }

        /// <summary>Action: read</summary>
        public Action Read => Actions.Read;
        /// <summary>Action: write</summary>
        public Action Write => Actions.Write;
    }

    /// <summary>
    /// Resource: organizations
    /// </summary>
    public sealed class OrganizationsResource : ResourceBase
    {
        internal OrganizationsResource() : base("organizations") { }

        /// <summary>Action: read</summary>
        public Action Read => Actions.Read;
        /// <summary>Action: write</summary>
        public Action Write => Actions.Write;
    }

    /// <summary>
    /// Resource: permissions
    /// </summary>
    public sealed class PermissionsResource : ResourceBase
    {
        internal PermissionsResource() : base("permissions") { }

        /// <summary>Action: read</summary>
        public Action Read => Actions.Read;
        /// <summary>Action: write</summary>
        public Action Write => Actions.Write;
    }

    /// <summary>
    /// Resource: report-config
    /// </summary>
    public sealed class ReportConfigResource : ResourceBase
    {
        internal ReportConfigResource() : base("report-config") { }

        /// <summary>Action: read</summary>
        public Action Read => Actions.Read;
        /// <summary>Action: write</summary>
        public Action Write => Actions.Write;
    }

    /// <summary>
    /// Resource: reports
    /// </summary>
    public sealed class ReportsResource : ResourceBase
    {
        internal ReportsResource() : base("reports") { }

        /// <summary>Action: export</summary>
        public Action Export => Actions.Export;
        /// <summary>Action: read</summary>
        public Action Read => Actions.Read;
        /// <summary>Action: write</summary>
        public Action Write => Actions.Write;
    }

    /// <summary>
    /// Resource: roles
    /// </summary>
    public sealed class RolesResource : ResourceBase
    {
        internal RolesResource() : base("roles") { }

        /// <summary>Action: read</summary>
        public Action Read => Actions.Read;
        /// <summary>Action: write</summary>
        public Action Write => Actions.Write;
    }

    /// <summary>
    /// Resource: sensor-config
    /// </summary>
    public sealed class SensorConfigResource : ResourceBase
    {
        internal SensorConfigResource() : base("sensor-config") { }

        /// <summary>Action: configure</summary>
        public Action Configure => Actions.Configure;
        /// <summary>Action: read</summary>
        public Action Read => Actions.Read;
        /// <summary>Action: write</summary>
        public Action Write => Actions.Write;
    }

    /// <summary>
    /// Resource: sensor-health
    /// </summary>
    public sealed class SensorHealthResource : ResourceBase
    {
        internal SensorHealthResource() : base("sensor-health") { }

        /// <summary>Action: read</summary>
        public Action Read => Actions.Read;
        /// <summary>Action: write</summary>
        public Action Write => Actions.Write;
    }

    /// <summary>
    /// Resource: sensor-readings
    /// </summary>
    public sealed class SensorReadingsResource : ResourceBase
    {
        internal SensorReadingsResource() : base("sensor-readings") { }

        /// <summary>Action: read</summary>
        public Action Read => Actions.Read;
        /// <summary>Action: write</summary>
        public Action Write => Actions.Write;
    }

    /// <summary>
    /// Resource: sensor-types
    /// </summary>
    public sealed class SensorTypesResource : ResourceBase
    {
        internal SensorTypesResource() : base("sensor-types") { }

        /// <summary>Action: read</summary>
        public Action Read => Actions.Read;
        /// <summary>Action: write</summary>
        public Action Write => Actions.Write;
    }

    /// <summary>
    /// Resource: sensors
    /// </summary>
    public sealed class SensorsResource : ResourceBase
    {
        internal SensorsResource() : base("sensors") { }

        /// <summary>Action: read</summary>
        public Action Read => Actions.Read;
        /// <summary>Action: write</summary>
        public Action Write => Actions.Write;
    }

    /// <summary>
    /// Resource: site-overview
    /// </summary>
    public sealed class SiteOverviewResource : ResourceBase
    {
        internal SiteOverviewResource() : base("site-overview") { }

        /// <summary>Action: read</summary>
        public Action Read => Actions.Read;
        /// <summary>Action: write</summary>
        public Action Write => Actions.Write;
    }

    /// <summary>
    /// Resource: sites
    /// </summary>
    public sealed class SitesResource : ResourceBase
    {
        internal SitesResource() : base("sites") { }

        /// <summary>Action: read</summary>
        public Action Read => Actions.Read;
        /// <summary>Action: write</summary>
        public Action Write => Actions.Write;
    }

    /// <summary>
    /// Resource: system-overview
    /// </summary>
    public sealed class SystemOverviewResource : ResourceBase
    {
        internal SystemOverviewResource() : base("system-overview") { }

        /// <summary>Action: read</summary>
        public Action Read => Actions.Read;
        /// <summary>Action: write</summary>
        public Action Write => Actions.Write;
    }

    /// <summary>
    /// Resource: thresholds
    /// </summary>
    public sealed class ThresholdsResource : ResourceBase
    {
        internal ThresholdsResource() : base("thresholds") { }

        /// <summary>Action: read</summary>
        public Action Read => Actions.Read;
        /// <summary>Action: write</summary>
        public Action Write => Actions.Write;
    }

    /// <summary>
    /// Resource: users
    /// </summary>
    public sealed class UsersResource : ResourceBase
    {
        internal UsersResource() : base("users") { }

        /// <summary>Action: read</summary>
        public Action Read => Actions.Read;
        /// <summary>Action: write</summary>
        public Action Write => Actions.Write;
    }

    // Resource instances
    /// <summary>Resource instance for alert-rules</summary>
    public static AlertRulesResource AlertRules { get; } = new();

    /// <summary>Resource instance for alerts</summary>
    public static AlertsResource Alerts { get; } = new();

    /// <summary>Resource instance for alerts-config</summary>
    public static AlertsConfigResource AlertsConfig { get; } = new();

    /// <summary>Resource instance for equipment</summary>
    public static EquipmentResource Equipment { get; } = new();

    /// <summary>Resource instance for equipment-config</summary>
    public static EquipmentConfigResource EquipmentConfig { get; } = new();

    /// <summary>Resource instance for equipment-status</summary>
    public static EquipmentStatusResource EquipmentStatus { get; } = new();

    /// <summary>Resource instance for ingestion</summary>
    public static IngestionResource Ingestion { get; } = new();

    /// <summary>Resource instance for ingestion-config</summary>
    public static IngestionConfigResource IngestionConfig { get; } = new();

    /// <summary>Resource instance for ingestion-runs</summary>
    public static IngestionRunsResource IngestionRuns { get; } = new();

    /// <summary>Resource instance for organizations</summary>
    public static OrganizationsResource Organizations { get; } = new();

    /// <summary>Resource instance for permissions</summary>
    public static PermissionsResource Permissions { get; } = new();

    /// <summary>Resource instance for report-config</summary>
    public static ReportConfigResource ReportConfig { get; } = new();

    /// <summary>Resource instance for reports</summary>
    public static ReportsResource Reports { get; } = new();

    /// <summary>Resource instance for roles</summary>
    public static RolesResource Roles { get; } = new();

    /// <summary>Resource instance for sensor-config</summary>
    public static SensorConfigResource SensorConfig { get; } = new();

    /// <summary>Resource instance for sensor-health</summary>
    public static SensorHealthResource SensorHealth { get; } = new();

    /// <summary>Resource instance for sensor-readings</summary>
    public static SensorReadingsResource SensorReadings { get; } = new();

    /// <summary>Resource instance for sensor-types</summary>
    public static SensorTypesResource SensorTypes { get; } = new();

    /// <summary>Resource instance for sensors</summary>
    public static SensorsResource Sensors { get; } = new();

    /// <summary>Resource instance for site-overview</summary>
    public static SiteOverviewResource SiteOverview { get; } = new();

    /// <summary>Resource instance for sites</summary>
    public static SitesResource Sites { get; } = new();

    /// <summary>Resource instance for system-overview</summary>
    public static SystemOverviewResource SystemOverview { get; } = new();

    /// <summary>Resource instance for thresholds</summary>
    public static ThresholdsResource Thresholds { get; } = new();

    /// <summary>Resource instance for users</summary>
    public static UsersResource Users { get; } = new();

    /// <summary>
    /// Gets all available resources
    /// </summary>
    public static IReadOnlyList<IResource> All { get; } = new IResource[]
    {
        AlertRules,
        Alerts,
        AlertsConfig,
        Equipment,
        EquipmentConfig,
        EquipmentStatus,
        Ingestion,
        IngestionConfig,
        IngestionRuns,
        Organizations,
        Permissions,
        ReportConfig,
        Reports,
        Roles,
        SensorConfig,
        SensorHealth,
        SensorReadings,
        SensorTypes,
        Sensors,
        SiteOverview,
        Sites,
        SystemOverview,
        Thresholds,
        Users,
    };
}
