// Code generated by CLI permission:generate; DO NOT EDIT manually.
// This file was generated at 2026-02-05 05:43:33 UTC

namespace Shared.Permissions;

/// <summary>
/// Contains all role constants used in the RBAC system.
/// </summary>
public static class Roles
{
    /// <summary>Role: admin</summary>
    public const string Admin = "admin";

    /// <summary>Role: manager</summary>
    public const string Manager = "manager";

    /// <summary>Role: operator</summary>
    public const string Operator = "operator";

    /// <summary>Role: readonly</summary>
    public const string Readonly = "readonly";

    /// <summary>
    /// Gets all available roles
    /// </summary>
    public static IReadOnlyList<string> All { get; } =
    [
        Admin,
        Manager,
        Operator,
        Readonly
    ];
}
