// <auto-generated />
using System;
using Adapters.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Adapters.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260226230000_AddFirstOutOfRangeAtToSensor")]
    partial class AddFirstOutOfRangeAtToSensor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Shared.Entity.Admin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_admins_id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_admins_created_at_desc");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_admins_organization_id");

                    b.HasIndex("OrganizationId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ix_admins_organization_id_email_unique");

                    b.ToTable("admins", (string)null);
                });

            modelBuilder.Entity("Shared.Entity.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid>("SensorId")
                        .HasColumnType("uuid")
                        .HasColumnName("sensor_id");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("severity");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<decimal>("ThresholdMax")
                        .HasColumnType("numeric")
                        .HasColumnName("threshold_max");

                    b.Property<decimal>("ThresholdMin")
                        .HasColumnType("numeric")
                        .HasColumnName("threshold_min");

                    b.Property<DateTime>("TriggeredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("triggered_at");

                    b.Property<decimal>("TriggeredValue")
                        .HasColumnType("numeric")
                        .HasColumnName("triggered_value");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_alerts_id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_alerts_created_at_desc");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_alerts_organization_id");

                    b.HasIndex("SensorId")
                        .HasDatabaseName("ix_alerts_sensor_id");

                    b.HasIndex("SiteId");

                    b.HasIndex("SensorId", "Status")
                        .HasDatabaseName("ix_alerts_sensor_id_status");

                    b.ToTable("alerts", (string)null);
                });

            modelBuilder.Entity("Shared.Entity.AlertEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<Guid>("AlertId")
                        .HasColumnType("uuid")
                        .HasColumnName("alert_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("event_type");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_alert_events_id");

                    b.HasIndex("AlertId")
                        .HasDatabaseName("ix_alert_events_alert_id");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_alert_events_occurred_at");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_alert_events_organization_id");

                    b.ToTable("alert_events", (string)null);
                });

            modelBuilder.Entity("Shared.Entity.ApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key_hash");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.HasKey("Id")
                        .HasName("pk_api_keys_id");

                    b.HasIndex("KeyHash")
                        .IsUnique()
                        .HasDatabaseName("ix_api_keys_key_hash");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_api_keys_organization_id");

                    b.ToTable("api_keys", (string)null);
                });

            modelBuilder.Entity("Shared.Entity.CasbinRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("V0")
                        .HasColumnType("text");

                    b.Property<string>("V1")
                        .HasColumnType("text");

                    b.Property<string>("V2")
                        .HasColumnType("text");

                    b.Property<string>("V3")
                        .HasColumnType("text");

                    b.Property<string>("V4")
                        .HasColumnType("text");

                    b.Property<string>("V5")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CasbinRules");
                });

            modelBuilder.Entity("Shared.Entity.Equipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("EquipmentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("equipment_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_equipment_id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_equipment_created_at_desc");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_equipment_organization_id");

                    b.HasIndex("SiteId")
                        .HasDatabaseName("ix_equipment_site_id");

                    b.ToTable("equipment", (string)null);
                });

            modelBuilder.Entity("Shared.Entity.IngestionRejectedReading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("IngestionRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("ingestion_run_id");

                    b.Property<string>("RejectionReason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("rejection_reason");

                    b.Property<Guid?>("SensorId")
                        .HasColumnType("uuid")
                        .HasColumnName("sensor_id");

                    b.Property<int>("RowIndex")
                        .HasColumnType("integer")
                        .HasColumnName("row_index");

                    b.HasKey("Id")
                        .HasName("pk_ingestion_run_rejected_readings_id");

                    b.HasIndex("IngestionRunId")
                        .HasDatabaseName("ix_ingestion_run_rejected_readings_ingestion_run_id");

                    b.HasIndex("SensorId")
                        .HasDatabaseName("ix_ingestion_run_rejected_readings_sensor_id");

                    b.ToTable("ingestion_run_rejected_readings", (string)null);
                });

            modelBuilder.Entity("Shared.Entity.IngestionRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AcceptedRecords")
                        .HasColumnType("integer")
                        .HasColumnName("accepted_records");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<int>("RejectedRecords")
                        .HasColumnType("integer")
                        .HasColumnName("rejected_records");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<int>("TotalRecords")
                        .HasColumnType("integer")
                        .HasColumnName("total_records");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_ingestion_runs_id");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_ingestion_runs_organization_id");

                    b.ToTable("ingestion_runs", (string)null);
                });

            modelBuilder.Entity("Shared.Entity.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_organizations_id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_organizations_created_at_desc");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_organizations_slug_unique");

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("Shared.Entity.RoleMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<byte>("ColorB")
                        .HasColumnType("smallint")
                        .HasColumnName("color_b");

                    b.Property<byte>("ColorG")
                        .HasColumnType("smallint")
                        .HasColumnName("color_g");

                    b.Property<byte>("ColorR")
                        .HasColumnType("smallint")
                        .HasColumnName("color_r");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("role_metadata", (string)null);
                });

            modelBuilder.Entity("Shared.Entity.Sensor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("SensorTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("sensor_type_id");

                    b.Property<string>("Serial")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("serial");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("FirstOutOfRangeAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_out_of_range_at");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<Guid>("ThresholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("threshold_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_sensors_id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_sensors_created_at_desc");

                    b.HasIndex("EquipmentId")
                        .HasDatabaseName("ix_sensors_equipment_id");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_sensors_organization_id");

                    b.HasIndex("SensorTypeId")
                        .HasDatabaseName("ix_sensors_sensor_type_id");

                    b.HasIndex("Serial")
                        .HasDatabaseName("ix_sensors_serial");

                    b.HasIndex("ThresholdId")
                        .IsUnique()
                        .HasDatabaseName("ix_sensors_threshold_id_unique");

                    b.ToTable("sensors", (string)null);
                });

            modelBuilder.Entity("Shared.Entity.SensorReading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("IngestionRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("ingestion_run_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("SensorId")
                        .HasColumnType("uuid")
                        .HasColumnName("sensor_id");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp_utc");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_sensor_readings_id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_sensor_readings_created_at_desc");

                    b.HasIndex("IngestionRunId");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_sensor_readings_organization_id");

                    b.HasIndex("SensorId")
                        .HasDatabaseName("ix_sensor_readings_sensor_id");

                    b.HasIndex("OrganizationId", "TimestampUtc")
                        .HasDatabaseName("ix_sensor_readings_organization_id_timestamp_utc");

                    b.HasIndex("SensorId", "TimestampUtc")
                        .HasDatabaseName("ix_sensor_readings_sensor_id_timestamp_utc");

                    b.ToTable("sensor_readings", (string)null);
                });

            modelBuilder.Entity("Shared.Entity.SensorType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_sensor_types_id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_sensor_types_created_at_desc");

                    b.ToTable("sensor_types", (string)null);
                });

            modelBuilder.Entity("Shared.Entity.Site", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("postal_code");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("state");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_sites_id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_sites_created_at_desc");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_sites_organization_id");

                    b.ToTable("sites", (string)null);
                });

            modelBuilder.Entity("Shared.Entity.Threshold", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval")
                        .HasColumnName("duration");

                    b.Property<decimal>("Max")
                        .HasColumnType("numeric")
                        .HasColumnName("max");

                    b.Property<decimal>("Min")
                        .HasColumnType("numeric")
                        .HasColumnName("min");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_thresholds_id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_thresholds_created_at_desc");

                    b.ToTable("thresholds", (string)null);
                });

            modelBuilder.Entity("Shared.Entity.Admin", b =>
                {
                    b.HasOne("Shared.Entity.Organization", "Organization")
                        .WithMany("Admins")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_admins_organization_id");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Shared.Entity.AlertEvent", b =>
                {
                    b.HasOne("Shared.Entity.Alert", "Alert")
                        .WithMany("Events")
                        .HasForeignKey("AlertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_alert_events_alert_id");

                    b.HasOne("Shared.Entity.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_alert_events_organization_id");

                    b.Navigation("Alert");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Shared.Entity.Alert", b =>
                {
                    b.HasOne("Shared.Entity.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_alerts_equipment_id");

                    b.HasOne("Shared.Entity.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_alerts_organization_id");

                    b.HasOne("Shared.Entity.Sensor", "Sensor")
                        .WithMany()
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_alerts_sensor_id");

                    b.HasOne("Shared.Entity.Site", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_alerts_site_id");

                    b.Navigation("Equipment");

                    b.Navigation("Events");

                    b.Navigation("Organization");

                    b.Navigation("Sensor");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("Shared.Entity.ApiKey", b =>
                {
                    b.HasOne("Shared.Entity.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_api_keys_organization_id");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Shared.Entity.Equipment", b =>
                {
                    b.HasOne("Shared.Entity.Organization", "Organization")
                        .WithMany("Equipment")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_equipment_organization_id");

                    b.HasOne("Shared.Entity.Site", "Site")
                        .WithMany("Equipment")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_equipment_site_id");

                    b.Navigation("Organization");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("Shared.Entity.IngestionRejectedReading", b =>
                {
                    b.HasOne("Shared.Entity.IngestionRun", "IngestionRun")
                        .WithMany("RejectedReadings")
                        .HasForeignKey("IngestionRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ingestion_run_rejected_readings_ingestion_run_id");

                    b.Navigation("IngestionRun");
                });

            modelBuilder.Entity("Shared.Entity.IngestionRun", b =>
                {
                    b.HasOne("Shared.Entity.Organization", "Organization")
                        .WithMany("IngestionRuns")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ingestion_runs_organization_id");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Shared.Entity.Sensor", b =>
                {
                    b.HasOne("Shared.Entity.Equipment", "Equipment")
                        .WithMany("Sensors")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sensors_equipment_id");

                    b.HasOne("Shared.Entity.Organization", "Organization")
                        .WithMany("Sensors")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sensors_organization_id");

                    b.HasOne("Shared.Entity.SensorType", "SensorType")
                        .WithMany("Sensors")
                        .HasForeignKey("SensorTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sensors_sensor_type_id");

                    b.HasOne("Shared.Entity.Threshold", "Threshold")
                        .WithOne("Sensor")
                        .HasForeignKey("Shared.Entity.Sensor", "ThresholdId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sensors_threshold_id");

                    b.Navigation("Equipment");

                    b.Navigation("Organization");

                    b.Navigation("SensorType");

                    b.Navigation("Threshold");
                });

            modelBuilder.Entity("Shared.Entity.SensorReading", b =>
                {
                    b.HasOne("Shared.Entity.IngestionRun", "IngestionRun")
                        .WithMany("SensorReadings")
                        .HasForeignKey("IngestionRunId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_sensor_readings_ingestion_run_id");

                    b.HasOne("Shared.Entity.Organization", "Organization")
                        .WithMany("SensorReadings")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sensor_readings_organization_id");

                    b.HasOne("Shared.Entity.Sensor", "Sensor")
                        .WithMany("SensorReadings")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sensor_readings_sensor_id");

                    b.Navigation("IngestionRun");

                    b.Navigation("Organization");

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("Shared.Entity.Site", b =>
                {
                    b.HasOne("Shared.Entity.Organization", "Organization")
                        .WithMany("Sites")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sites_organization_id");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Shared.Entity.Equipment", b =>
                {
                    b.Navigation("Sensors");
                });

            modelBuilder.Entity("Shared.Entity.IngestionRun", b =>
                {
                    b.Navigation("RejectedReadings");

                    b.Navigation("SensorReadings");
                });

            modelBuilder.Entity("Shared.Entity.Organization", b =>
                {
                    b.Navigation("Admins");

                    b.Navigation("Equipment");

                    b.Navigation("IngestionRuns");

                    b.Navigation("SensorReadings");

                    b.Navigation("Sensors");

                    b.Navigation("Sites");
                });

            modelBuilder.Entity("Shared.Entity.Sensor", b =>
                {
                    b.Navigation("SensorReadings");
                });

            modelBuilder.Entity("Shared.Entity.SensorType", b =>
                {
                    b.Navigation("Sensors");
                });

            modelBuilder.Entity("Shared.Entity.Site", b =>
                {
                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("Shared.Entity.Threshold", b =>
                {
                    b.Navigation("Sensor");
                });
#pragma warning restore 612, 618
        }
    }
}
