// <auto-generated />
using System;
using Adapters.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Adapters.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Shared.Entity.Admin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_admins_id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_admins_created_at_desc");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_admins_organization_id");

                    b.HasIndex("OrganizationId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ix_admins_organization_id_email_unique");

                    b.ToTable("admins", (string)null);
                });

            modelBuilder.Entity("Shared.Entity.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid>("SensorId")
                        .HasColumnType("uuid")
                        .HasColumnName("sensor_id");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("severity");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<decimal>("ThresholdMax")
                        .HasColumnType("numeric")
                        .HasColumnName("threshold_max");

                    b.Property<decimal>("ThresholdMin")
                        .HasColumnType("numeric")
                        .HasColumnName("threshold_min");

                    b.Property<DateTime>("TriggeredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("triggered_at");

                    b.Property<decimal>("TriggeredValue")
                        .HasColumnType("numeric")
                        .HasColumnName("triggered_value");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_alerts_id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_alerts_created_at_desc");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_alerts_organization_id");

                    b.HasIndex("SensorId")
                        .HasDatabaseName("ix_alerts_sensor_id");

                    b.HasIndex("SiteId");

                    b.HasIndex("SensorId", "Status")
                        .HasDatabaseName("ix_alerts_sensor_id_status");

                    b.ToTable("alerts", (string)null);
                });

            modelBuilder.Entity("Shared.Entity.AlertEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<Guid>("AlertId")
                        .HasColumnType("uuid")
                        .HasColumnName("alert_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("event_type");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_alert_events_id");

                    b.HasIndex("AlertId")
                        .HasDatabaseName("ix_alert_events_alert_id");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_alert_events_occurred_at");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_alert_events_organization_id");

                    b.ToTable("alert_events", (string)null);
                });

            modelBuilder.Entity("Shared.Entity.ApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key_hash");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.HasKey("Id")
                        .HasName("pk_api_keys_id");

                    b.HasIndex("KeyHash")
                        .IsUnique()
                        .HasDatabaseName("ix_api_keys_key_hash");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_api_keys_organization_id");

                    b.ToTable("api_keys", (string)null);
                });

            modelBuilder.Entity("Shared.Entity.CasbinRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("V0")
                        .HasColumnType("text");

                    b.Property<string>("V1")
                        .HasColumnType("text");

                    b.Property<string>("V2")
                        .HasColumnType("text");

                    b.Property<string>("V3")
                        .HasColumnType("text");

                    b.Property<string>("V4")
                        .HasColumnType("text");

                    b.Property<string>("V5")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CasbinRules");
                });

            modelBuilder.Entity("Shared.Entity.Equipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("EquipmentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("equipment_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_equipment_id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_equipment_created_at_desc");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_equipment_organization_id");

                    b.HasIndex("SiteId")
                        .HasDatabaseName("ix_equipment_site_id");

                    b.ToTable("equipment", (string)null);
                });

            modelBuilder.Entity("Shared.Entity.IngestionRejectedReading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("IngestionRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("ingestion_run_id");

                    b.Property<string>("RejectionReason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("rejection_reason");

                    b.Property<int>("RowIndex")
                        .HasColumnType("integer")
                        .HasColumnName("row_index");

                    b.Property<Guid?>("SensorId")
                        .HasColumnType("uuid")
                        .HasColumnName("sensor_id");

                    b.HasKey("Id")
                        .HasName("pk_ingestion_run_rejected_readings_id");

                    b.HasIndex("IngestionRunId")
                        .HasDatabaseName("ix_ingestion_run_rejected_readings_ingestion_run_id");

                    b.HasIndex("SensorId")
                        .HasDatabaseName("ix_ingestion_run_rejected_readings_sensor_id");

                    b.ToTable("ingestion_run_rejected_readings", (string)null);
                });

            modelBuilder.Entity("Shared.Entity.IngestionRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AcceptedRecords")
                        .HasColumnType("integer")
                        .HasColumnName("accepted_records");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<int>("RejectedRecords")
                        .HasColumnType("integer")
                        .HasColumnName("rejected_records");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<int>("TotalRecords")
                        .HasColumnType("integer")
                        .HasColumnName("total_records");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_ingestion_runs_id");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_ingestion_runs_organization_id");

                    b.ToTable("ingestion_runs", (string)null);
                });

            modelBuilder.Entity("Shared.Entity.IntakeShipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ArrivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("arrived_at");

                    b.Property<decimal?>("ColdChainTempC")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("cold_chain_temp_c");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Driver")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("driver");

                    b.Property<string>("PoReference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("po_reference");

                    b.Property<string>("ReceivedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("received_by");

                    b.Property<string>("ReceivingZone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("receiving_zone");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Vehicle")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("vehicle");

                    b.HasKey("Id")
                        .HasName("pk_intake_shipments_id");

                    b.HasIndex("ArrivedAt")
                        .IsDescending()
                        .HasDatabaseName("idx_intake_shipments_arrived_at");

                    b.HasIndex("PoReference")
                        .IsUnique();

                    b.HasIndex("SiteId")
                        .HasDatabaseName("idx_intake_shipments_site_id");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("idx_intake_shipments_supplier_id");

                    b.ToTable("intake_shipments", (string)null);
                });

            modelBuilder.Entity("Shared.Entity.IntakeShipmentLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("CostPerUnit")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("cost_per_unit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("LotCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("lot_code");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<decimal>("Qty")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("qty");

                    b.Property<Guid>("ShipmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("shipment_id");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unit");

                    b.HasKey("Id")
                        .HasName("pk_intake_shipment_lines_id");

                    b.HasIndex("LotCode");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("idx_intake_lines_product_id");

                    b.HasIndex("ShipmentId")
                        .HasDatabaseName("idx_intake_lines_shipment_id");

                    b.ToTable("intake_shipment_lines", (string)null);
                });

            modelBuilder.Entity("Shared.Entity.InventoryCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_categories_id");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("Shared.Entity.InventoryProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("KgPerBox")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("kg_per_box");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("price");

                    b.Property<int>("ShelfLifeDays")
                        .HasColumnType("integer")
                        .HasColumnName("shelf_life_days");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sku");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_products_id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("idx_products_category_id");

                    b.HasIndex("Sku")
                        .IsUnique()
                        .HasDatabaseName("idx_products_sku");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("Shared.Entity.InventorySite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_inv_sites_id");

                    b.ToTable("inv_sites", (string)null);
                });

            modelBuilder.Entity("Shared.Entity.Lot", b =>
                {
                    b.Property<string>("LotCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("lot_code");

                    b.Property<decimal>("CostPerUnit")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("cost_per_unit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("EntryAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("entry_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<decimal>("Qty")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("qty");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<Guid?>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("zone");

                    b.HasKey("LotCode")
                        .HasName("pk_lots_lot_code");

                    b.HasIndex("EntryAt")
                        .HasDatabaseName("idx_lots_entry_at");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("idx_lots_expires_at");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("idx_lots_product_id");

                    b.HasIndex("SiteId")
                        .HasDatabaseName("idx_lots_site_id");

                    b.HasIndex("SupplierId");

                    b.ToTable("lots", (string)null);
                });

            modelBuilder.Entity("Shared.Entity.Movement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DestSiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("dest_site_id");

                    b.Property<string>("LotCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("lot_code");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("performed_by");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<decimal>("Qty")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("qty");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unit");

                    b.HasKey("Id")
                        .HasName("pk_movements_id");

                    b.HasIndex("DestSiteId");

                    b.HasIndex("LotCode")
                        .HasDatabaseName("idx_movements_lot_code");

                    b.HasIndex("OccurredAt")
                        .IsDescending()
                        .HasDatabaseName("idx_movements_occurred_at");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("idx_movements_product_id");

                    b.HasIndex("SiteId")
                        .HasDatabaseName("idx_movements_site_id");

                    b.HasIndex("Type")
                        .HasDatabaseName("idx_movements_type");

                    b.ToTable("movements", (string)null);
                });

            modelBuilder.Entity("Shared.Entity.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_organizations_id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_organizations_created_at_desc");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_organizations_slug_unique");

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("Shared.Entity.RecommendedAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("SensorTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("sensor_type_id");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("severity");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_recommended_actions_id");

                    b.HasIndex("SensorTypeId", "Severity")
                        .HasDatabaseName("ix_recommended_actions_sensor_type_id_severity");

                    b.ToTable("recommended_actions", (string)null);
                });

            modelBuilder.Entity("Shared.Entity.RoleMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<byte>("ColorB")
                        .HasColumnType("smallint")
                        .HasColumnName("color_b");

                    b.Property<byte>("ColorG")
                        .HasColumnType("smallint")
                        .HasColumnName("color_g");

                    b.Property<byte>("ColorR")
                        .HasColumnType("smallint")
                        .HasColumnName("color_r");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("role_metadata", (string)null);
                });

            modelBuilder.Entity("Shared.Entity.Sensor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment_id");

                    b.Property<DateTime?>("FirstOutOfRangeAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_out_of_range_at");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("SensorTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("sensor_type_id");

                    b.Property<string>("Serial")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("serial");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("ThresholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("threshold_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_sensors_id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_sensors_created_at_desc");

                    b.HasIndex("EquipmentId")
                        .HasDatabaseName("ix_sensors_equipment_id");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_sensors_organization_id");

                    b.HasIndex("SensorTypeId")
                        .HasDatabaseName("ix_sensors_sensor_type_id");

                    b.HasIndex("Serial")
                        .HasDatabaseName("ix_sensors_serial");

                    b.HasIndex("ThresholdId")
                        .IsUnique()
                        .HasDatabaseName("ix_sensors_threshold_id_unique");

                    b.ToTable("sensors", (string)null);
                });

            modelBuilder.Entity("Shared.Entity.SensorReading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("IngestionRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("ingestion_run_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("SensorId")
                        .HasColumnType("uuid")
                        .HasColumnName("sensor_id");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp_utc");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_sensor_readings_id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_sensor_readings_created_at_desc");

                    b.HasIndex("IngestionRunId");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_sensor_readings_organization_id");

                    b.HasIndex("SensorId")
                        .HasDatabaseName("ix_sensor_readings_sensor_id");

                    b.HasIndex("OrganizationId", "TimestampUtc")
                        .HasDatabaseName("ix_sensor_readings_organization_id_timestamp_utc");

                    b.HasIndex("SensorId", "TimestampUtc")
                        .HasDatabaseName("ix_sensor_readings_sensor_id_timestamp_utc");

                    b.ToTable("sensor_readings", (string)null);
                });

            modelBuilder.Entity("Shared.Entity.SensorType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_sensor_types_id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_sensor_types_created_at_desc");

                    b.ToTable("sensor_types", (string)null);
                });

            modelBuilder.Entity("Shared.Entity.Site", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("postal_code");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("state");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_sites_id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_sites_created_at_desc");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_sites_organization_id");

                    b.ToTable("sites", (string)null);
                });

            modelBuilder.Entity("Shared.Entity.SiteZone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.HasKey("Id")
                        .HasName("pk_site_zones_id");

                    b.HasIndex("SiteId")
                        .HasDatabaseName("idx_site_zones_site_id");

                    b.HasIndex("SiteId", "Name")
                        .IsUnique();

                    b.ToTable("site_zones", (string)null);
                });

            modelBuilder.Entity("Shared.Entity.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_suppliers_id");

                    b.ToTable("suppliers", (string)null);
                });

            modelBuilder.Entity("Shared.Entity.Threshold", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval")
                        .HasColumnName("duration");

                    b.Property<decimal>("Max")
                        .HasColumnType("numeric")
                        .HasColumnName("max");

                    b.Property<decimal>("Min")
                        .HasColumnType("numeric")
                        .HasColumnName("min");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_thresholds_id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_thresholds_created_at_desc");

                    b.ToTable("thresholds", (string)null);
                });

            modelBuilder.Entity("Shared.Entity.Admin", b =>
                {
                    b.HasOne("Shared.Entity.Organization", "Organization")
                        .WithMany("Admins")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_admins_organization_id");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Shared.Entity.Alert", b =>
                {
                    b.HasOne("Shared.Entity.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_alerts_equipment_id");

                    b.HasOne("Shared.Entity.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_alerts_organization_id");

                    b.HasOne("Shared.Entity.Sensor", "Sensor")
                        .WithMany()
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_alerts_sensor_id");

                    b.HasOne("Shared.Entity.Site", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_alerts_site_id");

                    b.Navigation("Equipment");

                    b.Navigation("Organization");

                    b.Navigation("Sensor");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("Shared.Entity.AlertEvent", b =>
                {
                    b.HasOne("Shared.Entity.Alert", "Alert")
                        .WithMany("Events")
                        .HasForeignKey("AlertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_alert_events_alert_id");

                    b.HasOne("Shared.Entity.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_alert_events_organization_id");

                    b.Navigation("Alert");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Shared.Entity.ApiKey", b =>
                {
                    b.HasOne("Shared.Entity.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_api_keys_organization_id");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Shared.Entity.Equipment", b =>
                {
                    b.HasOne("Shared.Entity.Organization", "Organization")
                        .WithMany("Equipment")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_equipment_organization_id");

                    b.HasOne("Shared.Entity.Site", "Site")
                        .WithMany("Equipment")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_equipment_site_id");

                    b.Navigation("Organization");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("Shared.Entity.IngestionRejectedReading", b =>
                {
                    b.HasOne("Shared.Entity.IngestionRun", "IngestionRun")
                        .WithMany("RejectedReadings")
                        .HasForeignKey("IngestionRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ingestion_run_rejected_readings_ingestion_run_id");

                    b.Navigation("IngestionRun");
                });

            modelBuilder.Entity("Shared.Entity.IngestionRun", b =>
                {
                    b.HasOne("Shared.Entity.Organization", "Organization")
                        .WithMany("IngestionRuns")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ingestion_runs_organization_id");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Shared.Entity.IntakeShipment", b =>
                {
                    b.HasOne("Shared.Entity.InventorySite", "Site")
                        .WithMany("IntakeShipments")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_intake_shipments_site_id");

                    b.HasOne("Shared.Entity.Supplier", "Supplier")
                        .WithMany("IntakeShipments")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_intake_shipments_supplier_id");

                    b.Navigation("Site");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Shared.Entity.IntakeShipmentLine", b =>
                {
                    b.HasOne("Shared.Entity.Lot", "Lot")
                        .WithMany("ShipmentLines")
                        .HasForeignKey("LotCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_intake_shipment_lines_lot_code");

                    b.HasOne("Shared.Entity.InventoryProduct", "Product")
                        .WithMany("ShipmentLines")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_intake_shipment_lines_product_id");

                    b.HasOne("Shared.Entity.IntakeShipment", "Shipment")
                        .WithMany("Lines")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_intake_shipment_lines_shipment_id");

                    b.Navigation("Lot");

                    b.Navigation("Product");

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("Shared.Entity.InventoryProduct", b =>
                {
                    b.HasOne("Shared.Entity.InventoryCategory", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_products_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Shared.Entity.Lot", b =>
                {
                    b.HasOne("Shared.Entity.InventoryProduct", "Product")
                        .WithMany("Lots")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_lots_product_id");

                    b.HasOne("Shared.Entity.InventorySite", "Site")
                        .WithMany("Lots")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_lots_site_id");

                    b.HasOne("Shared.Entity.Supplier", "Supplier")
                        .WithMany("Lots")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_lots_supplier_id");

                    b.Navigation("Product");

                    b.Navigation("Site");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Shared.Entity.Movement", b =>
                {
                    b.HasOne("Shared.Entity.InventorySite", "DestSite")
                        .WithMany()
                        .HasForeignKey("DestSiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_movements_dest_site_id");

                    b.HasOne("Shared.Entity.Lot", "Lot")
                        .WithMany("Movements")
                        .HasForeignKey("LotCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_movements_lot_code");

                    b.HasOne("Shared.Entity.InventoryProduct", "Product")
                        .WithMany("Movements")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_movements_product_id");

                    b.HasOne("Shared.Entity.InventorySite", "Site")
                        .WithMany("Movements")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_movements_site_id");

                    b.Navigation("DestSite");

                    b.Navigation("Lot");

                    b.Navigation("Product");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("Shared.Entity.RecommendedAction", b =>
                {
                    b.HasOne("Shared.Entity.SensorType", "SensorType")
                        .WithMany()
                        .HasForeignKey("SensorTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_recommended_actions_sensor_type_id");

                    b.Navigation("SensorType");
                });

            modelBuilder.Entity("Shared.Entity.Sensor", b =>
                {
                    b.HasOne("Shared.Entity.Equipment", "Equipment")
                        .WithMany("Sensors")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sensors_equipment_id");

                    b.HasOne("Shared.Entity.Organization", "Organization")
                        .WithMany("Sensors")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sensors_organization_id");

                    b.HasOne("Shared.Entity.SensorType", "SensorType")
                        .WithMany("Sensors")
                        .HasForeignKey("SensorTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sensors_sensor_type_id");

                    b.HasOne("Shared.Entity.Threshold", "Threshold")
                        .WithOne("Sensor")
                        .HasForeignKey("Shared.Entity.Sensor", "ThresholdId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sensors_threshold_id");

                    b.Navigation("Equipment");

                    b.Navigation("Organization");

                    b.Navigation("SensorType");

                    b.Navigation("Threshold");
                });

            modelBuilder.Entity("Shared.Entity.SensorReading", b =>
                {
                    b.HasOne("Shared.Entity.IngestionRun", "IngestionRun")
                        .WithMany("SensorReadings")
                        .HasForeignKey("IngestionRunId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_sensor_readings_ingestion_run_id");

                    b.HasOne("Shared.Entity.Organization", "Organization")
                        .WithMany("SensorReadings")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sensor_readings_organization_id");

                    b.HasOne("Shared.Entity.Sensor", "Sensor")
                        .WithMany("SensorReadings")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sensor_readings_sensor_id");

                    b.Navigation("IngestionRun");

                    b.Navigation("Organization");

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("Shared.Entity.Site", b =>
                {
                    b.HasOne("Shared.Entity.Organization", "Organization")
                        .WithMany("Sites")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sites_organization_id");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Shared.Entity.SiteZone", b =>
                {
                    b.HasOne("Shared.Entity.InventorySite", "Site")
                        .WithMany("Zones")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_site_zones_site_id");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("Shared.Entity.Alert", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("Shared.Entity.Equipment", b =>
                {
                    b.Navigation("Sensors");
                });

            modelBuilder.Entity("Shared.Entity.IngestionRun", b =>
                {
                    b.Navigation("RejectedReadings");

                    b.Navigation("SensorReadings");
                });

            modelBuilder.Entity("Shared.Entity.IntakeShipment", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Shared.Entity.InventoryCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Shared.Entity.InventoryProduct", b =>
                {
                    b.Navigation("Lots");

                    b.Navigation("Movements");

                    b.Navigation("ShipmentLines");
                });

            modelBuilder.Entity("Shared.Entity.InventorySite", b =>
                {
                    b.Navigation("IntakeShipments");

                    b.Navigation("Lots");

                    b.Navigation("Movements");

                    b.Navigation("Zones");
                });

            modelBuilder.Entity("Shared.Entity.Lot", b =>
                {
                    b.Navigation("Movements");

                    b.Navigation("ShipmentLines");
                });

            modelBuilder.Entity("Shared.Entity.Organization", b =>
                {
                    b.Navigation("Admins");

                    b.Navigation("Equipment");

                    b.Navigation("IngestionRuns");

                    b.Navigation("SensorReadings");

                    b.Navigation("Sensors");

                    b.Navigation("Sites");
                });

            modelBuilder.Entity("Shared.Entity.Sensor", b =>
                {
                    b.Navigation("SensorReadings");
                });

            modelBuilder.Entity("Shared.Entity.SensorType", b =>
                {
                    b.Navigation("Sensors");
                });

            modelBuilder.Entity("Shared.Entity.Site", b =>
                {
                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("Shared.Entity.Supplier", b =>
                {
                    b.Navigation("IntakeShipments");

                    b.Navigation("Lots");
                });

            modelBuilder.Entity("Shared.Entity.Threshold", b =>
                {
                    b.Navigation("Sensor");
                });
#pragma warning restore 612, 618
        }
    }
}
